# Test API
@username={{$env USERNAME}}
@password={{$env PASSWORD}}
@email={{$env EMAIL}}
@Content={{$env CONTENT_TYPE}}
@Authorization={{$env AUTHORIZATION}}

### Identifition / Register account
POST http://localhost:8080/api/auth/local/register HTTP/1.1
Content-Type: {{Content}}

{
    "username": "{{username}}",
    "email": "{{email}}",
    "password": "{{password}}"
}


### Get all users
GET http://localhost:8080/api/users HTTP/1.1
Content-Type: {{Content}}

### Authentication / Login
POST http://localhost:8080/api/auth/local HTTP/1.1
Content-Type: {{Content}}

{
    "identifier": "{{email}}",
    "password": "{{password}}"
}

### Get profile
GET http://localhost:8080/api/users/me HTTP/1.1
Content-Type: {{Content}}
Authorization: {{Authorization}}

### Update Profile
PUT http://localhost:8080/api/users/1 HTTP/1.1
Content-Type: {{Content}}
Authorization: {{Authorization}}

{
    "username": "{{username}}"
}