# Test API
@username={{$env USERNAME}}
@password={{$env PASSWORD}}
@email={{$env EMAIL}}
@Content={{$env CONTENT_TYPE}}
@Authorization={{$env AUTHORIZATION}}
@post_register={{$env POST_REGISTER}}
@get_alluser={{@env GET_ALLUSER}}
@post_login={{@env POST_LOGIN}}
@get_profile={{@env GET_PROFILE}}
@put_updateprofile={{@env PUT_UPDATEPROFILE}}

### Identifition / Register account
POST {{post_register}}
Content-Type: {{Content}}

{
    "username": "{{username}}",
    "email": "{{email}}",
    "password": "{{password}}"
}


### Get all users
GET {{get_alluser}}
Content-Type: {{Content}}

### Authentication / Login
POST {{post_login}}
Content-Type: {{Content}}

{
    "identifier": "{{email}}",
    "password": "{{password}}"
}

### Get profile
GET {{get_profile}}
Content-Type: {{Content}}
Authorization: {{Authorization}}

### Update Profile
PUT {{put_updateprofile}}
Content-Type: {{Content}}
Authorization: {{Authorization}}

{
    "username": "{{username}}"
}