services:
 web:
  image: prawee/strapi:latest
  container_name: my_app_compose
  ports:
    - "8080:1337"
  environment:
    - POSTGRES_DB=thapana
    - POSTGRES_USER=thapana
    - POSTGRES_PASSWORD=thapana
  networks:
    my_custom_network:
      ipv4_address: 192.168.1.108