services:
  db:
    image: ${DATABASE_IMAGE}
    container_name: ${DATABASE_CONTAINER}
    ports:
      - "${DATABASE_PORT}"
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        
  app:
    image: ${APP_IMAGE}
    container_name: ${APP_CONTAINER}
    ports:
      - "${APP_PORT}"
    environment:
      - DATABASE_HOST=${APP_HOST}
      - DATABASE_PORT=${APP_INTRANALPORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}