services:
 db:
  image: postgres:latest
  container_name: my_db_compose
  ports:
    - "55432:5432"
  environment:
    - POSTGRES_DB=thapana
    - POSTGRES_USER=thapana
    - POSTGRES_PASSWORD=thapana

  web:
    image: prawee/strapi:latest
    container_name: my_app_compose
    ports:
      - "8081:1337"
    environment:
      - DATABASE_HOST=127.0.0.1
      - DATABASE_PORT=55432
      - DATABASE_NAME=thapana
      - DATABASE_USERNAME=thapana
      - DATABASE_PASSWORD=thapana